# Generated by Django 3.2.5 on 2021-11-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dkllapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notif',
            name='ligue',
        ),
    ]
