# Generated by Django 3.2.5 on 2021-07-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkllapp', '0002_candidat_ligue_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
