# Generated by Django 3.2.5 on 2021-11-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkllapp', '0002_remove_notif_ligue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidat',
            old_name='brigade',
            new_name='equipe_tv',
        ),
        migrations.AddField(
            model_name='candidat',
            name='chemin_img',
            field=models.CharField(default='Blanche', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidat',
            name='form_id',
            field=models.CharField(default='c00', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidat',
            name='statut',
            field=models.CharField(default='In', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidat',
            name='statut_bool',
            field=models.BooleanField(default=True),
        ),
    ]
