# Generated by Django 3.2.5 on 2021-12-22 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dkllapp', '0003_auto_20211117_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='insert_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
