# Generated by Django 3.2.5 on 2021-12-26 23:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dkllapp', '0004_equipe_insert_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligue_id', models.CharField(max_length=100)),
                ('user_id', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('candidat_id', models.IntegerField(default=0)),
                ('regle_id', models.IntegerField(default=0)),
                ('episode', models.IntegerField(default=0)),
                ('typage', models.IntegerField(default=0)),
                ('points_1', models.IntegerField(default=0)),
                ('points_2', models.IntegerField(default=0)),
                ('points_3', models.IntegerField(default=0)),
                ('somme_points_poulains', models.IntegerField(default=0)),
                ('somme_points_podium', models.IntegerField(default=0)),
                ('somme_points_gagnant', models.IntegerField(default=0)),
                ('somme_points_selon_types', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dkllapp_points',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='membre',
            name='insert_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
