# Generated by Django 3.2.5 on 2021-12-27 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dkllapp', '0005_auto_20211227_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('url', 'URL'), ('image', 'Image'), ('video', 'Video Clip')], max_length=100, verbose_name='Type')),
                ('url', models.CharField(max_length=255, verbose_name='Media URL')),
                ('text', models.TextField(verbose_name='Parsed media text')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
            },
        ),
        migrations.CreateModel(
            name='Blip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('in_reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dkllapp.blip', verbose_name='Reply to blip')),
                ('media', models.ManyToManyField(blank=True, null=True, to='dkllapp.Media', verbose_name='Media')),
            ],
            options={
                'verbose_name': 'Blip',
                'verbose_name_plural': 'Blips',
            },
        ),
    ]
