# Generated by Django 3.2.5 on 2021-12-28 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dkllapp', '0006_blip_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='mur',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dkllapp.mur'),
        ),
    ]
