# Generated by Django 3.2.5 on 2021-12-28 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dkllapp', '0007_mur_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mur',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
