# Generated by Django 3.2.5 on 2021-12-28 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dkllapp', '0008_mur_last_modified'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pronostic',
            new_name='Guess',
        ),
        migrations.RenameModel(
            old_name='Quotidien',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='guess',
            old_name='pronostic',
            new_name='proposition',
        ),
    ]
