# Generated by Django 3.2.5 on 2021-12-29 11:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dkllapp', '0009_auto_20211229_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guess',
            old_name='quotidien',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='enonce',
        ),
        migrations.RemoveField(
            model_name='question',
            name='propositions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='reponse',
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=999)),
                ('pertinence', models.BooleanField(default=False)),
                ('insert_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dkllapp.question')),
            ],
        ),
        migrations.AlterField(
            model_name='guess',
            name='proposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dkllapp.proposition'),
        ),
    ]
