# Generated by Django 3.2.5 on 2021-12-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkllapp', '0010_auto_20211229_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsFeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('feu', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dkllapp_points_feu',
                'managed': False,
            },
        ),
    ]
