# Generated by Django 4.0 on 2022-02-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkllapp', '0011_pointsfeu'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='lien',
            field=models.CharField(default='', max_length=999),
        ),
    ]
