# Generated by Django 4.0 on 2022-02-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkllapp', '0012_notif_lien'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipesFaites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('ligue_id', models.IntegerField(default=0)),
                ('episode', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dkllapp_equipes_faites',
                'managed': False,
            },
        ),
    ]
